# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:very_good_analysis/analysis_options.2.4.0.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - prefer_single_quotes: true
    - avoid_classes_with_only_static_members: false
#     - camel_case_types

analyzer:
  exclude:
    - "**.g.dart"
#     - path/to/excluded/files/**
